version: "3"
networks:
  mygeektime:
    driver: bridge
volumes:
  pgdata:
services:
  postgres:
    image: postgres:16-alpine
    hostname: "postgres"
    restart: always
    user: root
    networks:
      - mygeektime
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mygeektime
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init/:/docker-entrypoint-initdb.d/
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5432:5432"
  server:
    hostname: mygeektime
    image: zkep/mygeektime:latest
    privileged: true
    restart: always
    networks:
      - mygeektime
    command: server --config=config.yml
    ports:
      - "8090:8090"
    environment:
      - GIN_MODE=test
    volumes:
      - ./server/repo:/repo
      - ./server/config.yml:/config.yml
    depends_on:
      - postgres
